### ISSUE TITLE
2-train.py文件中的train_net函数是否需要加入“data_dir”和“label_dir”这两个变量？

### ISSUE THREAD

**Issue by QianMuXiao** [Ruikun-Li/3D-GCCN#2]
![image](https://github.com/Ruikun-Li/3D-GCCN/assets/40720829/5d3c613b-12be-4b93-96f7-1ce3c3e55bf8)

**Comment by Ruikun-Li** [comment]
你好，不好意思，这应该是我们在整理代码时候的一个疏漏，
这里的data_dir和label_dir对应的应该是上面定义的img_dir和prob_dir。因此将上面的img_dir和prob_dir改为data_dir和label_dir就可以了。稍后我们会更新一下代码。

**Comment by QianMuXiao** [comment]
谢谢 @Ruikun-Li

**Comment by Ruikun-Li** [comment]
不客气
